# Generated by Django 6.0.2 on 2026-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_alter_ticket_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='abierto'),
        ),
    ]
